### ISSUE TITLE
Call to 'node -e "require('nan')"'

### ISSUE THREAD

**Issue by gantarone** [jpenalbae/r2-scripts#2]
Hi , 
after npm install i get this error:
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/XXX/r2-scripts/decompiler/node_modules/syspipe
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN rollback Rolling back nan@1.8.4 failed (this is probably harmless): /Users/XXX/r2-scripts/decompiler/node_modules/nan is not a child of /usr/local/lib
npm WARN rollback Rolling back syspipe@0.1.4 failed (this is probably harmless): /Users/XXX/r2-scripts/decompiler/node_modules/syspipe is not a child of /usr/local/lib
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: syspipe@0.1.4 (../../../Users/XXX/r2-scripts/decompiler/node_modules/syspipe):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: syspipe@0.1.4 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ decompiler@0.1.0
updated 1 package in 4.69s

PS System: OSX Sierra
Please Help

**Comment by jpenalbae** [comment]
You can ignore those messages, those errors are part of an optional dependency.
